PARSER_FILES := \
interface/arg.c \
interface/ast_node.c \
interface/pipeline.c \
interface/redirect.c \
interface/simple_command.c \
interface/subshell.c \
validator/apply_parser_rule.c \
validator/is_ok.c \
validator/syntax_validator.c \
validator/scope_grammar.c \
validator/scope_operator.c \
validator/scope_terminal.c \
mapper.c \
parse_command_heredoc.c \
parse_command_utils.c \
parse_command.c \
parse_list.c \
parse_logical.c \
parse_pipeline.c \
parse_subshell.c \
parser.c \
