services:
  minishell:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minishell
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
