EXECUTOR_FILES := \
core/exec_background.c \
core/exec_command.c \
core/exec_pipeline.c \
core/exec_subshell.c \
core/oneshot.c \
core/safe_exit.c \
convert_args_to_argv.c \
env_serialize.c \
exec_engine.c \
executor.c \
expander/arg_node_new.c \
expander/expand_command.c \
expander/expand_variable_utils.c \
expander/expand_variable.c \
expander/expand_wildcard.c \
expander/handle_node_expansion.c \
expander/remove_quote.c \
expander/scan_files.c \
expander/substitute_variables.c \
find_path.c \
job/ast_to_str_utils.c \
job/ast_to_str.c \
job/job_sync.c \
job/job_controller.c \
job/job_utils.c \
job/job_wait.c \
job/job.c \
redirect/generate_hd_filename.c \
redirect/heredoc_prepare_all.c \
redirect/redirect_apply.c \
redirect/redirect_stdio.c \
traverse_ast.c \
